services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=todo
      - DB_USERNAME=todo
      - DB_PASSWORD=secret
    depends_on:
      - db
    command: bash -c "composer install && npm install && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mariadb:11.3
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=url_shortener
      - MYSQL_USER=url_shortener
      - MYSQL_PASSWORD=secret
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/main.sql

volumes:
  db_data: 