services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: url_shortener_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=url_shortener
      - DB_USERNAME=url_shortener
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
    depends_on:
      - db
      - redis
    command: bash -c "composer install && npm install && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mariadb:11.3
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=url_shortener
      - MYSQL_USER=url_shortener
      - MYSQL_PASSWORD=secret
    volumes:
      - ./database:/docker-entrypoint-initdb.d:delegated
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/main.sql

  redis:
    image: redis:alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  queue-worker:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: url_shortener_queue
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      - DB_HOST=db
      - DB_DATABASE=url_shortener
      - DB_USERNAME=url_shortener
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
    depends_on:
      - app
      - redis
    command: php artisan queue:work --tries=3 --backoff=3 --queue=default

volumes:
  db_data:
  redis_data: 